sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t irtiza/dock_react -f Dockerfile.dev .

script:
  - docker run -e CI=true irtiza/dock_react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'dock_react'
  env: 'Dockreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-290918986524'
  bucket_path: 'dock_react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
